# Generated by Django 2.2.4 on 2019-08-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gallery.Category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gallery.Location'),
        ),
    ]
